### ISSUE TITLE
Write after end error

### ISSUE THREAD

**Issue by piraka9011** [Tarteel-io/tarteel-voice#4]
The following error occurs in `handleReceivedData` method of the `RecognitionClient` class. This occurs when switching streams if the audio time is too long.
Before: 
```
this.recognizeStreams[this.currentRecognizeStreamIdx].end()
```
After:
```
try {
  this.recognizeStreams[this.currentRecognizeStreamIdx].end()
} catch (error) {
  console.error(error);
  this.onError(error)
}
```
Not tested tho, needs to be validated 

Error trace:
```
Error: write after end
    at writeAfterEnd (/home/piraka/tarteel_ws/Tarteel-voice/node_modules/wav/node_modules/readable-stream/lib/_stream_writable.js:161:12)
    at Writer.Writable.write (/home/piraka/tarteel_ws/Tarteel-voice/node_modules/wav/node_modules/readable-stream/lib/_stream_writable.js:208:5)
    at e.handleDataFileSave (/home/piraka/tarteel_ws/Tarteel-voice/build/bundle.js:1:4621)
    at Socket.<anonymous> (/home/piraka/tarteel_ws/Tarteel-voice/build/bundle.js:1:2437)
    at Socket.emit (events.js:189:13)
    at /home/piraka/tarteel_ws/Tarteel-voice/node_modules/socket.io/lib/socket.js:528:12
    at process._tickCallback (internal/process/next_tick.js:61:11)
Emitted 'error' event at:
    at writeAfterEnd (/home/piraka/tarteel_ws/Tarteel-voice/node_modules/wav/node_modules/readable-stream/lib/_stream_writable.js:163:10)
    at Writer.Writable.write (/home/piraka/tarteel_ws/Tarteel-voice/node_modules/wav/node_modules/readable-stream/lib/_stream_writable.js:208:5)
    [... lines matching original stack trace ...]
    at process._tickCallback (internal/process/next_tick.js:61:11)
[nodemon] app crashed - waiting for file changes before starting...
```

**Comment by fdalvi** [comment]
Hmm I'll look into this, but we do have a test case with audio > 2 mins  (i.e. two stream switches) which works, so I think this is not stemming from the long audio length. Do you have a sample test case/audio by any chance?
